name: 30-minute-cron
on:
  workflow_dispatch:
  
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call meteor
        run: |
          curl --request GET \
          --url 'http://w3bsite.meteorapp.com/' \
