# This is a basic workflow to help you get started with Actions

name: cron

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cron:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: callfitg
      - id: step1
        run: |
          curl --request GET \
          --url 'https://fitg.vercel.app/#/' \
          ::set-output name=test::
