# This is a basic workflow to help you get started with Actions

name: cron

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: callfitg
        run: |
          curl --request GET \
          --url 'https://fitg.vercel.app/#/' \
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          workflow_output2:
            description: "The job output"
            value: ${{ jobs.callfitg }}
