name: 15-minute-cron
on:
  workflow_dispatch:
  
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our app
        run: |
          curl --request GET \
          --url 'https://fitg.vercel.app/#/' \
